### ISSUE TITLE
Create config.php problem

### ISSUE THREAD

**Issue by SalihCanBinboga** [ZeroByter/zeropanelv2#15]
**Describe the bug**
a not create config.php

**To Reproduce**
I'm filling in the information at the first entry, and I'm pressing OK.Refreshing page and the config.php file does not occur

**Expected behavior**
a create config.php

Were you viewing the panel on desktop or mobile?:
- Desktop

**Comment by ZeroByter** [comment]
https://github.com/ZeroByter/zeropanelv2/issues/4
and
https://github.com/ZeroByter/zeropanelv2/issues/9
are similar, although I don't remember how I fixed them.

Do you have Teamspeak or Discord? I can connect and try to fix the problem with you live.
If not, the problem is difficult for me to reproduce and fix because it is not occurring on my setup. I am using XAMPP.

**Comment by SalihCanBinboga** [comment]
ts.armaturk.org

**Comment by ZeroByter** [comment]
I can't right now, but I will be on tomorrow at around the same time.

**Comment by SalihCanBinboga** [comment]
Thank you problem solved with you
