### ISSUE TITLE
Setup page refreshes after entering details and pressing "Setup Panel"

### ISSUE THREAD

**Issue by Infamous-Nathan** [ZeroByter/zeropanelv2#30]
For some reason whenever I try to set the panel up on the setup page, fill out all the details and press "Setup Panel" the page instantly refreshes and I have to fill out the details again. It just keeps doing this and I can't get to the next page for some reason.

**Comment by ZeroByter** [comment]
This is likely because you have placed the panel files not in the root
folder of your Apache server, what I mean is that you might be accessing it
like this: `mywebsite.com/admin/panel/`, and the panel is probably stored
somewhere like: `/htdocs/admin/panel/` or something similar.

If this is the case, there is no real fix for this, currently, so just move
the panel into the root Apache folder, access it normally, then you can
move it back to where you want the panel to be, and in the `config.php`
file, set the `linksOffset` and the `resourceLinksOffset` accordingly.

This has actually become such a common issue I think I will try to get a
patch for this today.

**Comment by Infamous-Nathan** [comment]
Hello,

The panel actually is in the root folder, so I'm not sure what's causing this. The only thing is that I'm not using the Altis Life framework, I'm using a custom framework, so not sure if that's why, but I was hoping to try it out to see if any parts of the panel will work with my server's framework.

**Comment by ZeroByter** [comment]
I tried replicating this in my XAMPP server but couldn't.
You guys got Discord or TeamSpeak? I'll be happy to drop by and we can use Teamviewer or something to figure this out together.

**Comment by Infamous-Nathan** [comment]
That would be good. I just wanted to check though first, does your panel work with other frameworks, or is it only compatible with Altis Life. If it's only compatible with Altis Life then that explains the issues I'm having lol.

**Comment by ZeroByter** [comment]
Should theoretically work with other frameworks fine, but even if that were the problem I don't think it would appear in the setup page.

Question, when you load the setup page, is the CSS loaded fine, or is it just the HTML with no styling?

**Comment by Infamous-Nathan** [comment]
This is how it looks: https://gyazo.com/333abc7cd0d490bb47d95d35ad11791f.

I'm assuming that's how it's meant to look?

**Comment by ZeroByter** [comment]
Nope, meaning it's probably the error I was talking about.

Give me a Discord/Teamspeak link and we'll take a closer look.

**Comment by Infamous-Nathan** [comment]
Okay, and add me on Discord my name is Nathan Turner#9540.

**Comment by ZeroByter** [comment]
Issue was the panel not being in the root htdocs folder.
