### ISSUE TITLE
Ban

### ISSUE THREAD

**Issue by vertigonetwork** [ZeroByter/zeropanelv2#5]
The ban.php isnt working it dont add people to the ban. Txt everything ells works just not the ban also logs arnt working under player name it has an erro would love to see these Fixed

**Comment by ZeroByter** [comment]
These features are working fine in my local environment, and they also work at another community which suggests the problem is in your end.

Most likely your MySQL bans table doesn't match the PHP code's syntax.

Either consider going into /classes/bans.php and at the top of the file you should see PHP code describing how your MySQL bans table is supposed to look like. Or I can help you fix the bug directly through TeamViewer. I am free pretty much anytime.

And if you haven't updated, you should update to the latest version of the panel for more security patches and features.

**Comment by vertigonetwork** [comment]
Where would one select the ban. Txt file tho as its not entering them there

**Comment by ZeroByter** [comment]
What? If you want my help you will need to precisely describe your error and how you are trying to fix it.
